name: Fetch Latest APKs

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  fetch-apks:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch APK from GitHub Release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "tanujnotes/Olauncher"
          tag: "latest"
          fileName: "*.apk"
          out-file-path: "./downloads/github"
          
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.apk || true
          if git diff --cached --quiet; then
            echo "No new APKs to commit."
          else
            git commit -m "Update APKs"
            git push
